#!/usr/bin/env python

import sys

from rqt_gui.main import Main
#from rqt_plot_lf.plot import Plot

#plugin = 'dragon_control_panel.plot.Plot'
main = Main()
sys.exit(main.main(sys.argv , standalone='dragon_control_panel'))
