#!/usr/bin/env python

import sys

from rqt_gui.main import Main
#from rqt_plot_single.plot import Plot

#plugin = 'rqt_plot_single.plot.Plot'
main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_plot_single'))
