#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_plot_entire.plot import Plot

plugin = 'rqt_plot_entire.plot.Plot'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv , standalone=plugin))
